### ISSUE TITLE
Make the component work with Vaadin 23

### ISSUE THREAD

**Issue by mstahv** [Klaudeta/grid-pagination#22]
In current state, if you run the test server, the default test view gives you some JS errors. Those should be fixed to cut a V23 compatible release. Most probably things related to lit 2 etc.

There is also a Java compilation error.

**Comment by mstahv** [comment]
@gl0b3 maybe you forgot to commit some changes? I worked on this a bit and got the Java side to compile, but then there are these Lit things, that tend to contempt my nerves 😬

**Comment by mstahv** [comment]
Pushed my current work to a branch, gotta do something else for a while.

**Comment by gl0b3** [comment]
@mstahv I pushed everything except the generated frontend files (frontend\index.html, frontend\generated\index.ts, frontend\generated\vaadin-featureflags.ts, vite.config.ts, vite.generated.ts,vide-devmode.ts). The only problem for in Java side was that in the PaginatedGrid.InnerQuery constructors called getPageSize() and this throwed error. I modified to call pagination.getPageSize(). But I also pushed this modification.

**Comment by mstahv** [comment]
Yeah, did the same thing. But the client side was also broken for me, at least in dev mode I get exceptions. Might be that it kind of works though, in JS way 😁

**Comment by mstahv** [comment]
I think it works, but can't be 100% sure. I'll cut a release and let's see the responses.

**Comment by mstahv** [comment]
Oh right, 3.0.0 now available via Directory, pleas go ahead and try it out! https://vaadin.com/directory/component/grid-pagination

**Comment by gl0b3** [comment]
@mstahv I tried out with Vaadin starter app v23 (using this addon v3.0.0) and it seems okay. Thank you for your work!
