### ISSUE TITLE
Trouble with filter function

### ISSUE THREAD

**Issue by marcelbaumann** [Klaudeta/grid-pagination#9]
Hello

**Thanks** for your cool component. My application looks way more professional with it.

Is it possible that the filter function is no more working? I had problems with 2.0.10 and 2.0.09.
Now that the online demo is lifted 2.0.10, the filter is not working (I tried it in Google Chrome and Safari).

Before the update, **the version with 2.0.0 was working fine**. I could not check that the problem is. The filter code goes directly to the standard Vaadin class. 

If you are short of time and could get me a hint of where to look, I could start looking for an explanation.

_It seems to be a refresh problem. When I set a filter in your online demo https://klaudeta.app.fi/grid-pagination-demo/ nothing happens. But as soon as I set the page size to any new value, the filtered rows are correctly displayed._

Sincerely

**Comment by marcelbaumann** [comment]
The problem is that getDataProvider on PaginatedGrid does not return the provider initially associated with the grid but the temporary ListDataProvider generated by PaginatedGrid. Therefore when adding filters they are added to the wrong provider and discarded as soon as a page change occurs.

Suggest you add at least a comment describing the semantic change in Grid. It would be nice if a method is provided to access the original Provider which anyway stored in the PaginatedGrid instance.

Sincerely

**Comment by etrandafir93** [comment]
hello @marcelbaumann,  so it isn't possible to add some filter to the used provider? 
I have tried several things but none worked. In the example, a ListProvider is used, which is not really helpful.
Thanks, Emanuel.
